name: Build and Push Docker Image

on:
  workflow_dispatch:
  # Déclenche lors d'un push sur la branche main ou un tag versionné
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Par exemple, v1.0.0


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configurer Java (Java 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 3: Construire le projet avec Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Construire l'image Docker
      - name: Build Docker image
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker build -t ${{secrets.DOCKER_IMAGE_NAME}}:$VERSION . 

      # Step 6: Taguer et pousser l'image dans Docker Hub
      - name: Push Docker image
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)          
          
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME}}:${VERSION}


      # Step 7: Déploie de l'image docker sur l'EC2 d'AWS
      - name: Deploy to AWS EC2
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          terraform apply -auto-approve -var="docker_image_name=${{ secrets.DOCKER_IMAGE_NAME }}" -var="docker_image_version=${VERSION}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
